services:
  app:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - ./:/go/src/app
  
  db:
    image: mysql:8.1.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - data_store:/var/lib/mysql
    
volumes:
  data_store:
